import {useState,useMemo} from 'react';import {Link} from 'react-router-dom';import {MapPin,ListChecks,CheckCircle2,AlertTriangle,Radio,ZoomIn,ZoomOut,Upload,Bot} from 'lucide-react';
import {LineChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer,PieChart,Pie,Cell,BarChart,Bar} from 'recharts';
import {LOCATIONS,DEVICES,RISK_TREND} from '../data/demoData';import {useApp} from '../store';import {RiskBadge,Sim,Tag} from '../components/ui/Badge';import {RISK_AR,RISK_ORDER} from '../utils/risk';import {aiService} from '../services/ai/aiService';
import type {InspectionLocation} from '../types';
const MC={NORMAL:'bg-emerald-500',WARNING:'bg-amber-400',CRITICAL:'bg-red-500 animate-pulse',INSPECTED:'bg-cyan-400'};const ML={NORMAL:'طبيعي',WARNING:'تحذير',CRITICAL:'حرج',INSPECTED:'تم التفتيش'};
const PIE=['#34d399','#fbbf24','#fb923c','#f87171'];const ACTIONS=['اعتماد','رفض','طلب فحص إضافي','تحويل للصيانة','إضافة ملاحظة'];
export default function Dashboard(){const {role,tasks,findings,addFinding,decisions,review,notify}=useApp();
const [q,setQ]=useState('');const [rf,setRf]=useState('');const [sf,setSf]=useState('');const [ff,setFf]=useState('');const [zoom,setZoom]=useState(1);const [sel,setSel]=useState<InspectionLocation|null>(null);
const [imgs,setImgs]=useState(['IMG-T04-A','IMG-T04-B','IMG-T04-C']);const [pv,setPv]=useState(1);const [cmp,setCmp]=useState(false);
const [fid,setFid]=useState(findings[0]?.id);const [note,setNote]=useState('');const [busy,setBusy]=useState(false);
const facilities=[...new Set(LOCATIONS.map(l=>l.facility))];
const locs=useMemo(()=>LOCATIONS.filter(l=>(!rf||l.risk===rf)&&(!sf||l.state===sf)&&(!ff||l.facility===ff)&&(!q||(l.equipment+l.zone+l.id).toLowerCase().includes(q.toLowerCase()))),[q,rf,sf,ff]);
const active=tasks.filter(t=>['جديدة','مجدولة','قيد التنفيذ'].includes(t.status)).length;const alerts=LOCATIONS.filter(l=>l.risk==='critical'||l.risk==='high').length;
const kpi=[{l:'إجمالي مواقع التفتيش',v:LOCATIONS.length,i:MapPin,s:'+2 هذا الشهر',to:'/tasks?tab=locations'},{l:'المهام النشطة',v:active,i:ListChecks,s:'تتطلب متابعة',to:'/tasks?filter=active'},{l:'عمليات التفتيش المكتملة',v:tasks.filter(t=>t.status==='مكتملة').length+14,i:CheckCircle2,s:'ثابت',to:'/history'},{l:'التنبيهات والمخاطر',v:alerts,i:AlertTriangle,s:'حالات مرتفعة وحرجة',to:'/tasks?tab=locations'},{l:'الأجهزة والدرون',v:DEVICES.length,i:Radio,s:'محاكاة (SIMULATION)',to:'/'}];
const dist=RISK_ORDER.map((r,i)=>({name:RISK_AR[r],value:LOCATIONS.filter(l=>l.risk===r).length,c:PIE[i]}));
const cat=Object.entries(findings.reduce<Record<string,number>>((a,f)=>({...a,[f.kind]:(a[f.kind]||0)+1}),{})).map(([k,v])=>({k:k.slice(0,10),v}));
const f=findings.find(x=>x.id===fid);const canReview=role!=='collector';
const run=async()=>{setBusy(true);try{const r=await aiService.analyze(imgs[pv],'T-04','مجمع الواحة للتخزين');addFinding(r);setFid(r.id);notify('تم إنتاج نتيجة تحليل تجريبي')}catch{notify('فشل التحليل')}setBusy(false)};
return <>
{role==='inspector'&&<div className="card text-sm border-cyan-600">منظور المفتش: لديك {tasks.filter(t=>t.inspector==='خالد العتيبي'&&t.status!=='مكتملة').length} مهام مسندة. ابدأ من <Link className="text-cyan-300 underline" to="/tasks">المهام ومواقع التفتيش</Link>.</div>}
{role==='collector'&&<div className="card text-sm border-cyan-600">منظور جامع التقارير: راجع <Link className="text-cyan-300 underline" to="/reports">التقارير</Link> التي تحتاج استكمالاً. المراجعة الفنية للنتائج غير متاحة لهذا الدور.</div>}
<section aria-label="ملخص تشغيلي" className="grid grid-cols-2 lg:grid-cols-5 gap-3">{kpi.map(k=><Link key={k.l} to={k.to} className="card hover:border-cyan-500"><k.i className="text-cyan-400" size={20}/><div className="text-3xl font-bold mt-1">{k.v}</div><div className="text-sm">{k.l}</div><div className="text-xs text-slate-400">{k.s}</div></Link>)}</section>
<section className="card space-y-3"><div className="flex flex-wrap gap-2 items-center"><h2 className="font-bold">خريطة المتابعة</h2><Sim/>
<input className="inp" placeholder="بحث بالمعدة أو المنطقة" aria-label="بحث" value={q} onChange={e=>setQ(e.target.value)}/>
<select className="inp" aria-label="المنشأة" value={ff} onChange={e=>setFf(e.target.value)}><option value="">كل المنشآت</option>{facilities.map(x=><option key={x}>{x}</option>)}</select>
<select className="inp" aria-label="الخطورة" value={rf} onChange={e=>setRf(e.target.value)}><option value="">كل المخاطر</option>{RISK_ORDER.map(r=><option key={r} value={r}>{RISK_AR[r]}</option>)}</select>
<select className="inp" aria-label="حالة التفتيش" value={sf} onChange={e=>setSf(e.target.value)}><option value="">كل الحالات</option>{Object.entries(ML).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select>
<button className="btn2" aria-label="تكبير" onClick={()=>setZoom(Math.min(2,zoom+.25))}><ZoomIn size={16}/></button><button className="btn2" aria-label="تصغير" onClick={()=>setZoom(Math.max(1,zoom-.25))}><ZoomOut size={16}/></button></div>
<div className="grid lg:grid-cols-3 gap-3"><div className="lg:col-span-2 relative h-80 overflow-hidden rounded border border-cyan-900 bg-[linear-gradient(#18294d_1px,transparent_1px),linear-gradient(90deg,#18294d_1px,transparent_1px)] bg-[size:32px_32px]">
<div className="absolute inset-0 transition-transform" style={{transform:`scale(${zoom})`}}>{locs.map(l=><button key={l.id} onClick={()=>setSel(l)} aria-label={`${l.equipment} ${ML[l.state]}`} style={{left:l.x+'%',top:l.y+'%'}} className="absolute -translate-x-1/2 -translate-y-1/2 flex flex-col items-center"><span className={`w-4 h-4 rounded-full border-2 border-white ${MC[l.state]}`}/><span className="text-[10px] bg-navy-900/80 px-1 rounded">{l.equipment} · {ML[l.state]}</span></button>)}</div>
{!locs.length&&<div className="absolute inset-0 grid place-items-center text-slate-400">لا توجد نتائج مطابقة</div>}</div>
<div className="card text-sm">{sel?<div className="space-y-1"><h3 className="font-bold">{sel.equipment} <Tag>{sel.equipmentType}</Tag></h3><div>المنشأة: {sel.facility}</div><div>المنطقة: {sel.zone}</div><div>معرف المعدة: {sel.equipment}</div><div>حالة التفتيش: {ML[sel.state]}</div><div>آخر تفتيش: {sel.last}</div><div>الخطورة: <RiskBadge risk={sel.risk}/></div><div>آخر ملاحظة: {sel.note}</div></div>:<p className="text-slate-400">اختر علامة على الخريطة لعرض التفاصيل.</p>}</div></div></section>
<section className="card space-y-3"><div className="flex gap-2 items-center"><h2 className="font-bold">التصوير والمتابعة</h2><Sim>بيانات تصوير تجريبية</Sim></div>
<div className="grid md:grid-cols-3 gap-3"><div className="md:col-span-2">{cmp?<div className="grid grid-cols-2 gap-2">{[imgs[0],imgs[pv]].map((x,i)=><div key={i} className="h-48 rounded bg-gradient-to-br from-slate-700 to-cyan-900 grid place-items-center text-sm">{i?'بعد':'قبل'}: {x}</div>)}</div>:<div className="h-48 rounded bg-gradient-to-br from-slate-700 to-cyan-900 grid place-items-center overflow-hidden"><span style={{transform:'scale(1.3)'}}>{imgs[pv]} (معاينة)</span></div>}
<div className="text-xs text-slate-400 mt-1">معرف المعدة: T-04 · رقم التفتيش: INS-2041 · 2026-10-02 09:14</div></div>
<div className="space-y-2"><div className="grid grid-cols-3 gap-1">{imgs.map((x,i)=><button key={x+i} onClick={()=>setPv(i)} className={`h-14 rounded text-[10px] bg-navy-700 border ${pv===i?'border-cyan-400':'border-transparent'}`}>{x}</button>)}</div>
<button className="btn2 w-full" onClick={()=>setCmp(!cmp)}>{cmp?'عرض صورة واحدة':'مقارنة قبل/بعد'}</button>
<label className="btn2 w-full flex gap-1 justify-center cursor-pointer"><Upload size={14}/>رفع صورة وإرفاقها بالتفتيش<input type="file" accept="image/*" className="sr-only" onChange={e=>{const n=e.target.files?.[0]?.name;if(n){setImgs([...imgs,n]);notify('تم إرفاق الصورة بالتفتيش INS-2041')}}}/></label></div></div></section>
<section className="space-y-3"><div className="flex gap-2 items-center"><h2 className="font-bold text-lg">تحليل الذكاء الاصطناعي</h2><Sim>تحليل تجريبي</Sim><button className="btn ms-auto flex gap-1 items-center" disabled={busy} onClick={run}><Bot size={14}/>{busy?'جارٍ التحليل...':'تحليل الصورة المحددة'}</button></div>
<div className="grid lg:grid-cols-2 gap-3"><div className="card overflow-x-auto"><h3 className="font-semibold mb-2">الكشف</h3><table className="w-full text-sm"><thead><tr><th>الحالة</th><th>النوع</th><th>المعدة</th><th>الخطورة</th><th>الثقة</th><th>الوقت</th><th>الوضع</th></tr></thead><tbody>
{findings.map(x=><tr key={x.id} onClick={()=>setFid(x.id)} className={`cursor-pointer ${x.id===fid?'bg-cyan-900/30':''}`}><td>{x.id}</td><td>{x.kind}</td><td>{x.equipment}</td><td><RiskBadge risk={x.risk}/></td><td>{x.confidence}%</td><td className="text-xs">{x.time}</td><td className="text-xs">{x.status}</td></tr>)}</tbody></table></div>
<div className="card"><h3 className="font-semibold mb-2">التنبؤ بالمخاطر <span className="text-xs text-slate-400">(اتجاه مؤشر الخطورة)</span></h3><ResponsiveContainer width="100%" height={180}><LineChart data={RISK_TREND}><XAxis dataKey="m" stroke="#94a3b8"/><YAxis stroke="#94a3b8"/><Tooltip/><Line dataKey="v" stroke="#22d3ee" strokeWidth={2}/></LineChart></ResponsiveContainer></div>
<div className="card"><h3 className="font-semibold mb-2">نتائج التحليل</h3><div className="grid grid-cols-2 gap-2"><ResponsiveContainer width="100%" height={150}><PieChart><Pie data={dist} dataKey="value" nameKey="name" outerRadius={55}>{dist.map(d=><Cell key={d.name} fill={d.c}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><ResponsiveContainer width="100%" height={150}><BarChart data={cat}><XAxis dataKey="k" hide/><YAxis stroke="#94a3b8" allowDecimals={false}/><Tooltip/><Bar dataKey="v" fill="#22d3ee"/></BarChart></ResponsiveContainer></div><div className="text-xs text-slate-400">توزيع الخطورة (يسار) · الحالات حسب الفئة. أولوية التفتيش: PIPE-12 ثم T-04 ثم VLV-07.</div></div>
<div className="grid gap-3"><div className="card border-amber-700"><h3 className="font-semibold">تحليل AI (تجريبي)</h3>{f?<p className="text-sm">{f.kind} — {f.equipment} — ثقة {f.confidence}%. هذه توصية آلية وليست قرار سلامة.</p>:<p className="text-slate-400 text-sm">لا توجد حالات</p>}</div>
<div className="card border-emerald-700"><h3 className="font-semibold mb-2">المراجعة البشرية (القرار البشري)</h3>{canReview&&f?<><input className="inp w-full mb-2" placeholder="ملاحظات المراجع" aria-label="ملاحظات المراجع" value={note} onChange={e=>setNote(e.target.value)}/><div className="flex flex-wrap gap-1">{ACTIONS.map(a=><button key={a} className="btn2" onClick={()=>{if(a==='إضافة ملاحظة'&&!note.trim()){notify('اكتب الملاحظة أولاً');return}review(f.id,a,note);setNote('')}}>{a}</button>)}</div></>:<p className="text-xs text-slate-400">غير متاح لهذا الدور.</p>}
<ul className="mt-2 text-xs space-y-1">{decisions.filter(d=>d.findingId===fid).map((d,i)=><li key={i} className="border-t border-cyan-900/30 pt-1">{d.decision} — {d.reviewer} — {d.time}{d.note&&` — ${d.note}`}</li>)}</ul></div></div></div></section></>}
