import {useState} from 'react';import {useApp} from '../store';import {RiskBadge} from '../components/ui/Badge';import {RISK_ORDER,RISK_AR} from '../utils/risk';import type {Inspection} from '../types';
export default function InspectionHistory(){const {inspections}=useApp();const [q,setQ]=useState('');const [risk,setRisk]=useState('');const [from,setFrom]=useState('');const [insp,setInsp]=useState('');const [sel,setSel]=useState<Inspection|null>(null);
const list=inspections.filter(i=>(!q||(i.id+i.equipment+i.facility).includes(q))&&(!risk||i.risk===risk)&&(!from||i.date>=from)&&(!insp||i.inspector===insp)).sort((a,b)=>b.date.localeCompare(a.date));
const prev=sel?inspections.filter(i=>i.equipment===sel.equipment&&i.date<sel.date).sort((a,b)=>b.date.localeCompare(a.date))[0]:undefined;
return <>
<section className="card"><div className="flex flex-wrap gap-2 mb-3"><input className="inp" placeholder="بحث" aria-label="بحث" value={q} onChange={e=>setQ(e.target.value)}/><input type="date" className="inp" aria-label="من تاريخ" value={from} onChange={e=>setFrom(e.target.value)}/>
<select className="inp" aria-label="الخطورة" value={risk} onChange={e=>setRisk(e.target.value)}><option value="">كل المخاطر</option>{RISK_ORDER.map(r=><option key={r} value={r}>{RISK_AR[r]}</option>)}</select>
<select className="inp" aria-label="المفتش" value={insp} onChange={e=>setInsp(e.target.value)}><option value="">كل المفتشين</option>{[...new Set(inspections.map(i=>i.inspector))].map(i=><option key={i}>{i}</option>)}</select></div>
<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr><th>الرقم</th><th>التاريخ</th><th>الوقت</th><th>المنشأة</th><th>المعدة</th><th>المفتش</th><th>النتيجة</th><th>الخطورة</th><th>ملاحظات</th><th>التقرير</th><th>المراجعة</th><th/></tr></thead><tbody>
{list.map(i=><tr key={i.id}><td>{i.id}</td><td>{i.date}</td><td>{i.time}</td><td>{i.facility}</td><td>{i.equipment}</td><td>{i.inspector}</td><td>{i.result}</td><td><RiskBadge risk={i.risk}/></td><td>{i.notes}</td><td>{i.report}</td><td>{i.review}</td><td><button className="btn2" onClick={()=>setSel(i)}>فتح</button></td></tr>)}</tbody></table>{!list.length&&<p className="p-4 text-slate-400">لا توجد سجلات</p>}</div></section>
{sel&&<section className="card space-y-3"><h2 className="font-bold">{sel.id} — {sel.equipment}</h2><p className="text-xs text-amber-300">سجل للقراءة فقط: لا تُعدَّل السجلات التاريخية.</p>
<div className="grid md:grid-cols-2 gap-2 text-sm"><div>قائمة الفحص: 8 بنود مسجلة</div><div>الصور: 3 (بيانات تصوير تجريبية)</div><div>نتائج AI المفتوحة: {sel.openFindings}</div><div>القرارات البشرية: {sel.review}</div><div>التقرير: {sel.report}</div><div>الملاحظات: {sel.notes}</div></div>
<div className="text-xs text-slate-400">سجل النشاط: {sel.date} {sel.time} بدء التفتيش ← جمع البيانات ← تحليل تجريبي ← مراجعة بشرية ← حفظ</div>
<h3 className="font-semibold">مقارنة التفتيش السابق والحالي</h3>{prev?<table className="w-full text-sm"><thead><tr><th/><th>السابق {prev.id}</th><th>الحالي {sel.id}</th><th>التغير</th></tr></thead><tbody>
<tr><td>الخطورة</td><td><RiskBadge risk={prev.risk}/></td><td><RiskBadge risk={sel.risk}/></td><td>{RISK_ORDER.indexOf(sel.risk)>RISK_ORDER.indexOf(prev.risk)?'ارتفاع ▲':RISK_ORDER.indexOf(sel.risk)<RISK_ORDER.indexOf(prev.risk)?'انخفاض ▼':'ثابت'}</td></tr>
<tr><td>الحرارة (°م)</td><td>{prev.temp}</td><td>{sel.temp}</td><td>{sel.temp-prev.temp>0?'+':''}{sel.temp-prev.temp}</td></tr>
<tr><td>الملاحظات</td><td>{prev.notes}</td><td>{sel.notes}</td><td>جديدة: {Math.max(0,sel.notes-prev.notes)} · مغلقة: {Math.max(0,prev.notes-sel.notes)}</td></tr>
<tr><td>النتائج المفتوحة</td><td>{prev.openFindings}</td><td>{sel.openFindings}</td><td>{sel.openFindings-prev.openFindings}</td></tr></tbody></table>:<p className="text-sm text-slate-400">لا يوجد تفتيش سابق لهذه المعدة.</p>}</section>}</>}
