import {useState,useMemo} from 'react';import {Printer,FileDown,Archive} from 'lucide-react';import {useApp} from '../store';import {RiskBadge} from '../components/ui/Badge';import {RISK_ORDER} from '../utils/risk';import type {Report} from '../types';
export default function Reports(){const {role,reports,setReportStatus,decisions,findings}=useApp();const [q,setQ]=useState('');const [st,setSt]=useState('');const [sort,setSort]=useState<'date'|'risk'>('date');const [sel,setSel]=useState<Report|null>(null);const [conf,setConf]=useState(false);
const list=useMemo(()=>reports.filter(r=>(!st||r.status===st)&&(!q||(r.id+r.title+r.facility).includes(q))).sort((a,b)=>sort==='date'?b.date.localeCompare(a.date):RISK_ORDER.indexOf(b.risk)-RISK_ORDER.indexOf(a.risk)),[reports,q,st,sort]);
const c=(s:string)=>reports.filter(r=>r.status===s).length;const stats=[['إجمالي التقارير',reports.length],['جديدة',c('جديد')],['قيد المراجعة',c('قيد المراجعة')],['مكتملة',c('مكتمل')],['تحتاج استكمال',c('يحتاج استكمال')]];
const r=sel&&reports.find(x=>x.id===sel.id);const eq=r?.title.match(/[A-Z]+-?\d+(-\d+)?/)?.[0];const fl=findings.filter(f=>eq&&f.equipment===eq);
return <>
{role==='collector'&&<div className="card border-cyan-600 text-sm noprint">منظور جامع التقارير: {c('يحتاج استكمال')} تقارير تحتاج استكمالاً و{c('جديد')} جديدة للتحقق.</div>}
<section className="grid grid-cols-2 md:grid-cols-5 gap-3 noprint">{stats.map(([l,v])=><div key={l} className="card"><div className="text-2xl font-bold">{v}</div><div className="text-sm text-slate-400">{l}</div></div>)}</section>
<section className="card noprint"><div className="flex flex-wrap gap-2 mb-3"><input className="inp" placeholder="بحث" aria-label="بحث" value={q} onChange={e=>setQ(e.target.value)}/><select className="inp" aria-label="الحالة" value={st} onChange={e=>setSt(e.target.value)}><option value="">كل الحالات</option>{['جديد','قيد المراجعة','مكتمل','يحتاج استكمال','مؤرشف'].map(s=><option key={s}>{s}</option>)}</select>
<select className="inp" aria-label="الترتيب" value={sort} onChange={e=>setSort(e.target.value as 'date'|'risk')}><option value="date">الأحدث</option><option value="risk">الأعلى خطورة</option></select></div>
<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr><th>الرقم</th><th>العنوان</th><th>المنشأة</th><th>الموقع</th><th>المفتش</th><th>التاريخ</th><th>الخطورة</th><th>الحالة</th><th/></tr></thead><tbody>
{list.map(x=><tr key={x.id}><td>{x.id}</td><td>{x.title}</td><td>{x.facility}</td><td>{x.location}</td><td>{x.inspector}</td><td>{x.date}</td><td><RiskBadge risk={x.risk}/></td><td>{x.status}</td><td><button className="btn2" onClick={()=>setSel(x)}>عرض</button></td></tr>)}</tbody></table>{!list.length&&<p className="p-4 text-slate-400">لا توجد تقارير مطابقة</p>}</div></section>
{r&&<section className="card space-y-2"><div className="flex flex-wrap gap-2 noprint"><button className="btn2 flex gap-1" onClick={()=>window.print()}><Printer size={14}/>طباعة</button><button className="btn2 flex gap-1" onClick={()=>window.print()} title="اختر «حفظ كـ PDF» من نافذة الطباعة"><FileDown size={14}/>تصدير PDF</button>
<button className="btn2 flex gap-1" disabled={role==='inspector'||r.status==='مؤرشف'} onClick={()=>setConf(true)}><Archive size={14}/>أرشفة</button>{r.status==='يحتاج استكمال'&&role!=='inspector'&&<button className="btn" onClick={()=>setReportStatus(r.id,'قيد المراجعة')}>تم الاستكمال</button>}</div>
<h2 className="text-xl font-bold">VISIONGUARD — {r.title}</h2><p className="text-xs text-amber-300">بيانات محاكاة · تحليل تجريبي</p>
<dl className="grid md:grid-cols-3 gap-2 text-sm">{[['رقم التقرير',r.id],['تاريخ التفتيش',r.date],['المنشأة',r.facility],['المنطقة',r.location],['المعدة',eq||'—'],['المفتش',r.inspector],['حالة المعالجة',r.status]].map(([k,v])=><div key={k}><dt className="text-slate-400">{k}</dt><dd>{v}</dd></div>)}<div><dt className="text-slate-400">مستوى الخطورة</dt><dd><RiskBadge risk={r.risk}/></dd></div></dl>
<h3 className="font-semibold">نتائج AI (تجريبية)</h3><ul className="text-sm list-disc ms-5">{fl.map(f=><li key={f.id}>{f.kind} — ثقة {f.confidence}% — {f.status}</li>)}{!fl.length&&<li>لا نتائج</li>}</ul>
<h3 className="font-semibold">القرار البشري</h3><ul className="text-sm list-disc ms-5">{decisions.filter(d=>fl.some(f=>f.id===d.findingId)).map((d,i)=><li key={i}>{d.decision} — {d.reviewer} — {d.time}</li>)}{!decisions.some(d=>fl.some(f=>f.id===d.findingId))&&<li>لم يُسجَّل قرار بعد</li>}</ul>
<h3 className="font-semibold">الإجراءات المقترحة</h3><p className="text-sm">إعادة فحص المعدة خلال 14 يوماً ومتابعة الملاحظات المفتوحة مع فريق الصيانة.</p></section>}
{conf&&r&&<div role="alertdialog" aria-modal="true" className="fixed inset-0 z-50 bg-black/60 grid place-items-center"><div className="card space-y-3"><p>أرشفة التقرير {r.id}؟</p><div className="flex gap-2"><button className="btn" onClick={()=>{setReportStatus(r.id,'مؤرشف');setConf(false)}}>تأكيد</button><button className="btn2" onClick={()=>setConf(false)}>إلغاء</button></div></div></div>}</>}
